#!/bin/bash

set -e # If anything fails, stop the script.
set -u # If an undefined variable is expanded, stop the script.

root="$(git rev-parse --show-toplevel)"

function setup_symlinks() {
  cd "${root}/source"

  ln -fs ../bower_components/normalize.css/normalize.css
  ln -fs ../bower_components/css3-github-buttons/gh-buttons.css
  ln -fs ../bower_components/css3-github-buttons/gh-icons.png
  ln -fs ../bower_components/screenfull/dist/screenfull.js

  cd -
}

cd "${root}"

setup_symlinks

rm -rf dist
mkdir dist

sass source/pomodoro.scss dist/pomodoro.css

cp -LR source/* dist

$(npm bin)/postcss source/*.css -d dist/ --use autoprefixer

rm -f dist/*.{scss}

sed "s/{{timestamp}}/$(date +%Y-%m-%d)/g" dist/sitemap.xml > dist/sitemap.xml.tmp
mv dist/sitemap.xml.tmp dist/sitemap.xml

$(npm bin)/html-inline dist/index.html | html-minifier -c config/html-minifier.json > dist/index.html.min
mv dist/index.html.min dist/index.html
