#!/bin/bash

source .env

root="$(git rev-parse --show-toplevel)"

cd "${root}"

mkdir -p dist
coffee -cp pomodoro.coffee | uglifyjs -cm > dist/pomodoro.js
cp favicon.ico bower_components/normalize.css/normalize.css pomodoro.css index.html dist
cp bower_components/gh-buttons/index.css dist/gh-buttons.css

ssh -p ${DEPLOY_PORT} ${DEPLOY_USERNAME}@${DEPLOY_HOST} mkdir -p ${DEPLOY_PATH}
scp -P ${DEPLOY_PORT} dist/* ${DEPLOY_USERNAME}@${DEPLOY_HOST}:${DEPLOY_PATH}
