#!/bin/bash

source .env

root="$(git rev-parse --show-toplevel)"

cd "${root}"

mkdir -p dist
coffee -cp source/pomodoro.coffee > dist/pomodoro.js

cp -LR source/* dist

rm dist/*.{coffee,scss}

sed "s/{{timestamp}}/$(date +%Y-%m-%d)/g" dist/sitemap.xml > dist/sitemap.xml.tmp
mv dist/sitemap.xml.tmp dist/sitemap.xml

html-inline dist/index.html | html-minifier -c config/html-minifier.json > dist/index.html.min
mv dist/index.html.min dist/index.html

ssh -p ${DEPLOY_PORT} ${DEPLOY_USERNAME}@${DEPLOY_HOST} mkdir -p ${DEPLOY_PATH}
scp -P ${DEPLOY_PORT} dist/* ${DEPLOY_USERNAME}@${DEPLOY_HOST}:${DEPLOY_PATH}
