#!/bin/bash

PORT="${1:-8000}"
root="$(git rev-parse --show-toplevel)"

cd "${root}/source"

ln -fs ../bower_components/normalize.css/normalize.css
ln -fs ../bower_components/css3-github-buttons/gh-buttons.css
ln -fs ../bower_components/css3-github-buttons/gh-icons.png
ln -fs ../bower_components/screenfull/dist/screenfull.js
python -m SimpleHTTPServer ${PORT}
