#!/bin/bash

set -e # If anything fails, stop the script.
set -u # If an undefined variable is expanded, stop the script.

root="$(git rev-parse --show-toplevel)"

cd "${root}/source"

$(npm bin)/sass --watch . &

wait
